# frozen_string_literal: true

source 'https://rubygems.org'
gem 'coinbase'
gem 'coinbase-exchange'
gem 'colorize'
gem 'daemons'
gem 'dotenv'
gem 'eventmachine'
gem 'gserver'
gem 'moving_average'
gem 'percentage'
gem 'pry'
gem 'pushover'
gem 'redis'
gem 'rubocop'
gem 'solargraph'
gem 'tty'
